apiVersion: v1
kind: Secret
metadata:
  name: devopshub-secrets
  namespace: devops
type: Opaque
data:
  # Base64 encoded secrets
  OPENAI_API_KEY: "c2FtcGxlLWtleQ==" # "sample-key"
  DB_PASSWORD: "cGFzc3dvcmQ=" # "password"
