import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useMutation } from '@tanstack/react-query';
import { useDispatch } from 'react-redux';
import { authApi } from '../services/auth.api';
import { setCredentials } from '../store/authSlice';

export function LoginPage() { const [form, setForm] = useState({ email: '', password: '' }); const dispatch = useDispatch(); const navigate = useNavigate(); const mutation = useMutation({ mutationFn: authApi.login, onSuccess: (data) => { dispatch(setCredentials(data)); navigate('/'); } }); return <AuthCard title="Welcome back" subtitle="Sign in to your DevOpsHub AI workspace"><form onSubmit={(event) => { event.preventDefault(); mutation.mutate(form); }} className="space-y-4"><Input label="Email" type="email" value={form.email} onChange={(email) => setForm({ ...form, email })} /><Input label="Password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} />{mutation.error && <p className="text-sm text-rose-600">{mutation.error.response?.data?.error?.message || 'Unable to sign in.'}</p>}<button disabled={mutation.isPending} className="w-full rounded-lg bg-indigo-600 py-2.5 text-sm font-semibold text-white hover:bg-indigo-700 disabled:opacity-60">{mutation.isPending ? 'Signing in…' : 'Sign in'}</button></form><p className="mt-6 text-center text-sm text-slate-500">New here? <Link className="font-semibold text-indigo-600" to="/register">Create an account</Link></p></AuthCard>; }
export function AuthCard({ title, subtitle, children }) { return <div className="grid min-h-screen place-items-center bg-slate-50 p-4"><div className="w-full max-w-md rounded-2xl border border-slate-200 bg-white p-8 shadow-xl shadow-slate-200/50"><Link to="/" className="text-sm font-bold text-indigo-600">DevOpsHub AI</Link><h1 className="mt-6 text-2xl font-bold">{title}</h1><p className="mt-2 text-sm text-slate-500">{subtitle}</p><div className="mt-7">{children}</div></div></div>; }
function Input({ label, type, value, onChange }) { return <label className="block text-sm font-medium text-slate-700">{label}<input required type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1.5 w-full rounded-lg border border-slate-300 px-3 py-2.5 outline-none ring-indigo-500 focus:ring-2" /></label>; }
